"""Unit tests for planner.task (Sprint 2.8)."""

from __future__ import annotations

import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[2]
PLANNER_SRC = ROOT / "packages" / "planner" / "src"
sys.path.insert(0, str(PLANNER_SRC))

for _k in [k for k in list(sys.modules) if k == "planner" or k.startswith("planner.")]:
    sys.modules.pop(_k, None)

from planner.exceptions import InvalidTaskError  # noqa: E402
from planner.models import TaskPriority, TaskStatus  # noqa: E402
from planner.task import Task  # noqa: E402

# ----------------------------------------------------------------------
# Construction
# ----------------------------------------------------------------------


def test_task_default_id_autogenerated():
    t = Task(title="x")
    assert t.id.startswith("task-")


def test_task_default_status_pending():
    t = Task(title="x")
    assert t.status == TaskStatus.PENDING


def test_task_default_priority_normal():
    t = Task(title="x")
    assert t.priority == TaskPriority.NORMAL


def test_task_default_title_from_id_when_empty():
    t = Task()
    assert t.title == t.id


def test_task_post_init_copies_lists():
    deps = ["a", "b"]
    caps = ["x"]
    meta = {"k": "v"}
    t = Task(title="t", dependencies=deps, required_capabilities=caps, metadata=meta)
    deps.append("c")
    caps.append("y")
    meta["k"] = "changed"
    assert t.dependencies == ["a", "b"]
    assert t.required_capabilities == ["x"]
    assert t.metadata == {"k": "v"}


# ----------------------------------------------------------------------
# State transitions
# ----------------------------------------------------------------------


def test_mark_ready():
    t = Task(title="t")
    t.mark_ready()
    assert t.status == TaskStatus.READY


def test_mark_running_from_ready():
    t = Task(title="t")
    t.mark_ready()
    t.mark_running()
    assert t.status == TaskStatus.RUNNING


def test_mark_running_from_waiting():
    t = Task(title="t")
    t.mark_ready()
    t.mark_running()
    t.mark_waiting()
    t.mark_running()
    assert t.status == TaskStatus.RUNNING


def test_mark_completed():
    t = Task(title="t")
    t.mark_ready()
    t.mark_running()
    t.mark_completed()
    assert t.status == TaskStatus.COMPLETED


def test_mark_failed_records_error():
    t = Task(title="t")
    t.mark_ready()
    t.mark_running()
    t.mark_failed(error="boom")
    assert t.status == TaskStatus.FAILED
    assert t.metadata["last_error"] == "boom"


def test_mark_waiting():
    t = Task(title="t")
    t.mark_ready()
    t.mark_running()
    t.mark_waiting()
    assert t.status == TaskStatus.WAITING


def test_invalid_transition_raises():
    t = Task(title="t")
    # PENDING -> RUNNING is invalid (must go through READY).
    with pytest.raises(InvalidTaskError):
        t.mark_running()


def test_cancel_from_pending():
    t = Task(title="t")
    t.cancel()
    assert t.status == TaskStatus.CANCELLED


def test_cancel_idempotent():
    t = Task(title="t")
    t.cancel()
    t.cancel()  # should not raise
    assert t.status == TaskStatus.CANCELLED


def test_cancel_from_terminal_raises():
    t = Task(title="t")
    t.mark_ready()
    t.mark_running()
    t.mark_completed()
    with pytest.raises(InvalidTaskError):
        t.cancel()


def test_skip():
    t = Task(title="t")
    t.skip(reason="not needed")
    assert t.status == TaskStatus.SKIPPED
    assert t.metadata["skip_reason"] == "not needed"


def test_skip_idempotent():
    t = Task(title="t")
    t.skip()
    t.skip()  # should not raise


def test_reset():
    t = Task(title="t")
    t.mark_ready()
    t.mark_running()
    t.mark_failed(error="x")
    t.assigned_agent = "agent1"
    t.reset()
    assert t.status == TaskStatus.PENDING
    assert t.assigned_agent is None
    assert t.retry_count == 0
    assert "last_error" not in t.metadata


# ----------------------------------------------------------------------
# Retry
# ----------------------------------------------------------------------


def test_increment_retry():
    t = Task(title="t")
    n = t.increment_retry()
    assert n == 1
    assert t.retry_count == 1


def test_increment_retry_max_exhausted():
    t = Task(title="t", max_retries=2)
    t.increment_retry()
    t.increment_retry()
    with pytest.raises(InvalidTaskError):
        t.increment_retry()


def test_can_retry_when_failed():
    t = Task(title="t", max_retries=3)
    t.mark_ready()
    t.mark_running()
    t.mark_failed()
    assert t.can_retry is True
    t.increment_retry()
    t.increment_retry()
    t.increment_retry()
    assert t.can_retry is False


def test_cannot_retry_when_not_failed():
    t = Task(title="t")
    assert t.can_retry is False


# ----------------------------------------------------------------------
# Queries
# ----------------------------------------------------------------------


def test_is_terminal():
    t = Task(title="t")
    assert not t.is_terminal
    t.mark_ready()
    t.mark_running()
    t.mark_completed()
    assert t.is_terminal


def test_can_start():
    t = Task(title="t")
    assert t.can_start
    t.mark_ready()
    assert not t.can_start  # READY is not "can start" (can_start is for PENDING/FAILED)


# ----------------------------------------------------------------------
# Dependencies / capabilities
# ----------------------------------------------------------------------


def test_add_dependency():
    t = Task(title="t")
    t.add_dependency("other")
    assert "other" in t.dependencies


def test_add_dependency_idempotent():
    t = Task(title="t")
    t.add_dependency("other")
    t.add_dependency("other")
    assert t.dependencies.count("other") == 1


def test_add_dependency_self_raises():
    t = Task(title="t")
    with pytest.raises(InvalidTaskError):
        t.add_dependency(t.id)


def test_remove_dependency():
    t = Task(title="t", dependencies=["a", "b"])
    t.remove_dependency("a")
    assert t.dependencies == ["b"]


def test_remove_dependency_missing():
    t = Task(title="t", dependencies=["a"])
    t.remove_dependency("x")  # should not raise
    assert t.dependencies == ["a"]


def test_add_capability():
    t = Task(title="t")
    t.add_capability("code.generate")
    assert "code.generate" in t.required_capabilities


def test_add_capability_idempotent():
    t = Task(title="t")
    t.add_capability("x")
    t.add_capability("x")
    assert t.required_capabilities.count("x") == 1


def test_add_capability_empty_ignored():
    t = Task(title="t")
    t.add_capability("")
    assert t.required_capabilities == []


# ----------------------------------------------------------------------
# Metadata
# ----------------------------------------------------------------------


def test_update_metadata():
    t = Task(title="t", metadata={"a": 1})
    t.update_metadata(b=2)
    assert t.metadata["a"] == 1
    assert t.metadata["b"] == 2


def test_update_metadata_deep_merge():
    t = Task(title="t", metadata={"nested": {"x": 1}})
    t.update_metadata(nested={"y": 2})
    assert t.metadata["nested"] == {"x": 1, "y": 2}


# ----------------------------------------------------------------------
# Clone
# ----------------------------------------------------------------------


def test_clone_new_id():
    t = Task(title="t", description="d")
    clone = t.clone()
    assert clone.id != t.id
    assert clone.title == t.title
    assert clone.description == t.description


def test_clone_preserve_id():
    t = Task(title="t")
    clone = t.clone(new_id=False)
    assert clone.id == t.id


def test_clone_deep_copy_metadata():
    t = Task(title="t", metadata={"a": [1, 2]})
    clone = t.clone(new_id=False)
    clone.metadata["a"].append(3)
    assert t.metadata["a"] == [1, 2]


# ----------------------------------------------------------------------
# Serialization
# ----------------------------------------------------------------------


def test_serialize_roundtrip():
    t = Task(
        title="Test",
        description="A test task",
        priority=TaskPriority.HIGH,
        dependencies=["dep1"],
        required_capabilities=["code.generate"],
        assigned_agent="agent1",
        estimated_duration=10.5,
        estimated_tokens=500,
        estimated_cost=0.01,
        metadata={"key": "value"},
    )
    t.mark_ready()
    t.mark_running()
    t.mark_completed()
    s = t.serialize()
    t2 = Task.deserialize(s)
    assert t2.id == t.id
    assert t2.title == t.title
    assert t2.description == t.description
    assert t2.priority == t.priority
    assert t2.status == t.status
    assert t2.dependencies == t.dependencies
    assert t2.required_capabilities == t.required_capabilities
    assert t2.assigned_agent == t.assigned_agent
    assert t2.estimated_duration == t.estimated_duration
    assert t2.estimated_tokens == t.estimated_tokens
    assert t2.estimated_cost == t.estimated_cost
    assert t2.metadata == t.metadata


def test_deserialize_unknown_status_raises():
    s = {"id": "x", "title": "t", "status": "unknown_status"}
    with pytest.raises(InvalidTaskError):
        Task.deserialize(s)


def test_deserialize_unknown_priority_raises():
    s = {"id": "x", "title": "t", "status": "pending", "priority": "unknown_priority"}
    with pytest.raises(InvalidTaskError):
        Task.deserialize(s)


def test_deserialize_missing_fields_uses_defaults():
    s = {"id": "x", "title": "t"}
    t = Task.deserialize(s)
    assert t.status == TaskStatus.PENDING
    assert t.priority == TaskPriority.NORMAL
    assert t.dependencies == []


# ----------------------------------------------------------------------
# Equality / hashing
# ----------------------------------------------------------------------


def test_equality_by_id():
    t1 = Task(id="same", title="a")
    t2 = Task(id="same", title="b")
    assert t1 == t2


def test_inequality_different_id():
    t1 = Task(id="a", title="x")
    t2 = Task(id="b", title="x")
    assert t1 != t2


def test_hash_by_id():
    t1 = Task(id="same", title="a")
    t2 = Task(id="same", title="b")
    assert hash(t1) == hash(t2)
    # Can be used in a set.
    s = {t1, t2}
    assert len(s) == 1


def test_repr():
    t = Task(id="abc", title="My Task")
    r = repr(t)
    assert "abc" in r
    assert "My Task" in r
    assert "pending" in r
